# Generated by Django 3.0.4 on 2020-04-10 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeePersonDetails',
            new_name='EmployeeDetails',
        ),
        migrations.AlterModelTable(
            name='employeedetails',
            table='EmployeeDetails',
        ),
    ]
